version: '3'
services:
  # Ruby on Rails
  rails:
    build: .
    # default command
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    # use 3000 port
    ports:
      - 3000:3000
    # start mysql first
    depends_on:
      - mysql
    tty: true
    stdin_open: true
  # MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
    # use 3306 port
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
